steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vira-ai', '.']
    secretEnv: ['OPENAI_API_KEY']

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vira-ai']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'vira-ai',
        '--image',
        'gcr.io/$PROJECT_ID/vira-ai',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/openai-api-key/versions/latest
      env: 'OPENAI_API_KEY'
